version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: qbank
      POSTGRES_PASSWORD: qbank
      POSTGRES_DB: qbank
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qbank"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./qbank-backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://qbank:qbank@postgres:5432/qbank
      REDIS_URL: redis://redis:6379/0
      APP_SECRET: ${APP_SECRET:-dev-secret-change-me}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./qbank-backend:/app
      - ./analytics:/analytics

  worker:
    build:
      context: ./qbank-backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://qbank:qbank@postgres:5432/qbank
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python -m app.jobs.worker
    volumes:
      - ./qbank-backend:/app
      - ./analytics:/analytics

  admin-ui:
    build:
      context: ./admin-ui
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API: ${NEXT_PUBLIC_API:-http://localhost:8000}
    ports:
      - "4000:4000"
    depends_on:
      - api

volumes:
  postgres_data: