name: backend-ci
on: { push: { paths: ["qbank-backend/**","sql/**",".github/workflows/backend.yml"] }, pull_request: { paths: ["qbank-backend/**","sql/**",".github/workflows/backend.yml"] } }
jobs:
  api:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env: { POSTGRES_USER: qbank, POSTGRES_PASSWORD: qbank, POSTGRES_DB: qbank }
        ports: ["5432:5432"]
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]
    env:
      DATABASE_URL: postgresql+psycopg2://qbank:qbank@localhost:5432/qbank
      REDIS_URL: redis://localhost:6379/0
      APP_SECRET: ci-secret
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install -r qbank-backend/requirements.txt
      - name: Init DB schema
        run: |
          psql postgresql://qbank:qbank@localhost:5432/qbank -f sql/content_ddl.sql
          psql postgresql://qbank:qbank@localhost:5432/qbank -f sql/item_exposure_control.sql
          psql postgresql://qbank:qbank@localhost:5432/qbank -f sql/feature_flags.sql
          psql postgresql://qbank:qbank@localhost:5432/qbank -f sql/calibration_runs.sql
      - name: Launch API
        run: |
          nohup python -m uvicorn qbank-backend.app.main:app --host 0.0.0.0 --port 8000 &
          sleep 3
      - name: Pytest
        run: pytest -q qbank-backend/tests/test_api_smoke.py